#!/usr/bin/env bash
# display time for 12 hours and 59 minutes

time_h=0

while [ "$time_h" -le 12 ]; do
  echo "Hour: $time_h"
  
  time_m=1
  
  while [ "$time_m" -lt 60 ]; do
    echo "$time_m"
    time_m=$((minute + 1))
  done

  time_h=$((hour + 1))
done
