#!/usr/bin/env bash
# checker

alx_f="school"

if [ -e "$alx_f" ]; 
then

  echo "school file exists"

  if [ ! -s "$alx_f" ]; 
  then
    echo "school file is empty"

    if [ -f "$alx_f" ]; 
    then
      echo "school is a regular file"
    fi  

  else

    echo "school file is not empty"

    # checks if file is a regular file
    if [ -f "$alx_f" ]; then
      echo "school is a regular file"
    fi  
  
  fi

else
  
  echo "school file does not exist"

fi
